import { Geist, Geist_Mono } from 'next/font/google';
// import "./globals.css";
import './_styles/globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer/Footer';
import FadeInSection from './_components/FadeInSection';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Stephen Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header />
        {children}
        <FadeInSection>
          {' '}
          <Footer />
        </FadeInSection>
      </body>
    </html>
  );
}
